<?php
declare(strict_types=1);

// Api2newsEndpoint SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

Api2newsEndpointUtility::setRegistrar(function (Api2newsEndpointUtility $u): void {
    $u->clean = [Api2newsEndpointClean::class, 'call'];
    $u->done = [Api2newsEndpointDone::class, 'call'];
    $u->make_error = [Api2newsEndpointMakeError::class, 'call'];
    $u->feature_add = [Api2newsEndpointFeatureAdd::class, 'call'];
    $u->feature_hook = [Api2newsEndpointFeatureHook::class, 'call'];
    $u->feature_init = [Api2newsEndpointFeatureInit::class, 'call'];
    $u->fetcher = [Api2newsEndpointFetcher::class, 'call'];
    $u->make_fetch_def = [Api2newsEndpointMakeFetchDef::class, 'call'];
    $u->make_context = [Api2newsEndpointMakeContext::class, 'call'];
    $u->make_options = [Api2newsEndpointMakeOptions::class, 'call'];
    $u->make_request = [Api2newsEndpointMakeRequest::class, 'call'];
    $u->make_response = [Api2newsEndpointMakeResponse::class, 'call'];
    $u->make_result = [Api2newsEndpointMakeResult::class, 'call'];
    $u->make_point = [Api2newsEndpointMakePoint::class, 'call'];
    $u->make_spec = [Api2newsEndpointMakeSpec::class, 'call'];
    $u->make_url = [Api2newsEndpointMakeUrl::class, 'call'];
    $u->param = [Api2newsEndpointParam::class, 'call'];
    $u->prepare_auth = [Api2newsEndpointPrepareAuth::class, 'call'];
    $u->prepare_body = [Api2newsEndpointPrepareBody::class, 'call'];
    $u->prepare_headers = [Api2newsEndpointPrepareHeaders::class, 'call'];
    $u->prepare_method = [Api2newsEndpointPrepareMethod::class, 'call'];
    $u->prepare_params = [Api2newsEndpointPrepareParams::class, 'call'];
    $u->prepare_path = [Api2newsEndpointPreparePath::class, 'call'];
    $u->prepare_query = [Api2newsEndpointPrepareQuery::class, 'call'];
    $u->graphql_body = [Api2newsEndpointGraphql::class, 'body'];
    $u->graphql_errors = [Api2newsEndpointGraphql::class, 'errors'];
    $u->result_basic = [Api2newsEndpointResultBasic::class, 'call'];
    $u->result_body = [Api2newsEndpointResultBody::class, 'call'];
    $u->result_headers = [Api2newsEndpointResultHeaders::class, 'call'];
    $u->transform_request = [Api2newsEndpointTransformRequest::class, 'call'];
    $u->transform_response = [Api2newsEndpointTransformResponse::class, 'call'];
});
